// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvNXrZDF2qdc13AAJM3jt5PzuE42zETzA',
    appId: '1:1085438030835:web:4e1df2cd8ec344981b9886',
    messagingSenderId: '1085438030835',
    projectId: 'sportsinnoti',
    authDomain: 'sportsinnoti.firebaseapp.com',
    storageBucket: 'sportsinnoti.firebasestorage.app',
    measurementId: 'G-KL0CGXGER2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzSHhaeCid6B-RQU4dzsBO5qRQ9uJtub4',
    appId: '1:1085438030835:android:ffbeae6b40d6b7081b9886',
    messagingSenderId: '1085438030835',
    projectId: 'sportsinnoti',
    storageBucket: 'sportsinnoti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwr0lzy0aTLlf0ZdqtASy9w0Et8fo-dPg',
    appId: '1:1085438030835:ios:70aa3b5cebee8ec11b9886',
    messagingSenderId: '1085438030835',
    projectId: 'sportsinnoti',
    storageBucket: 'sportsinnoti.firebasestorage.app',
    iosBundleId: 'com.example.sportsin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwr0lzy0aTLlf0ZdqtASy9w0Et8fo-dPg',
    appId: '1:1085438030835:ios:70aa3b5cebee8ec11b9886',
    messagingSenderId: '1085438030835',
    projectId: 'sportsinnoti',
    storageBucket: 'sportsinnoti.firebasestorage.app',
    iosBundleId: 'com.example.sportsin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvNXrZDF2qdc13AAJM3jt5PzuE42zETzA',
    appId: '1:1085438030835:web:847a95c3265d7eb81b9886',
    messagingSenderId: '1085438030835',
    projectId: 'sportsinnoti',
    authDomain: 'sportsinnoti.firebaseapp.com',
    storageBucket: 'sportsinnoti.firebasestorage.app',
    measurementId: 'G-9768XGM71L',
  );
}
